#!/usr/bin/env bash
# Generated code from the API types' kubebuilder markers: the CRD (k8s-manifests/base/01-crd.yaml and the chart's
# crds/) and the deepcopy functions (k8s-operator/api/v1alpha1/zz_generated.deepcopy.go). None is edited by hand.
#
#   scripts/gen-manifests.sh write   regenerate both in place (make manifests)
#   scripts/gen-manifests.sh check   fail when either differs from what the markers generate (make manifests-check, CI)
#
# controller-gen is pinned (CONTROLLER_GEN_VERSION) and fetched through the Go module proxy with checksum verification.
set -euo pipefail

CONTROLLER_GEN_VERSION="${CONTROLLER_GEN_VERSION:-v0.20.1}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CRD_OUT="$ROOT/k8s-manifests/base/01-crd.yaml"
CHART_CRD="$ROOT/charts/predictive-autoscaler/crds/predictiveautoscalers.autoscaling.devkuban.com.yaml"
DEEPCOPY="api/v1alpha1/zz_generated.deepcopy.go"
mode="${1:-}"
case "$mode" in write|check) ;; *) echo "usage: $0 write|check" >&2; exit 2 ;; esac

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
# Generate in a copy of the module so that check never touches the working tree.
mkdir -p "$work/op" "$work/crd"
(cd "$ROOT/k8s-operator" && tar cf - --exclude ./bin go.mod go.sum api hack) | (cd "$work/op" && tar xf -)
# The copied deepcopy file is removed first, so a generator that silently produced nothing fails instead of passing.
rm -f "$work/op/$DEEPCOPY"
(
  cd "$work/op"
  go run "sigs.k8s.io/controller-tools/cmd/controller-gen@$CONTROLLER_GEN_VERSION" \
    object:headerFile=hack/boilerplate.go.txt crd paths=./api/... output:crd:dir="$work/crd"
)
[ -s "$work/op/$DEEPCOPY" ] || { echo "gen-manifests: controller-gen did not generate $DEEPCOPY" >&2; exit 1; }
crds=("$work"/crd/*.yaml)
[ "${#crds[@]}" -eq 1 ] || { echo "gen-manifests: expected one CRD, got ${#crds[@]}" >&2; exit 1; }
{
  echo "# GENERATED by controller-gen $CONTROLLER_GEN_VERSION from k8s-operator/api/v1alpha1 (scripts/gen-manifests.sh)."
  echo "# Do not edit: change the kubebuilder markers in the API types and run 'make manifests'."
  cat "${crds[0]}"
} > "$work/01-crd.yaml"

if [ "$mode" = write ]; then
  cp "$work/01-crd.yaml" "$CRD_OUT"
  cp "$work/01-crd.yaml" "$CHART_CRD"
  cp "$work/op/$DEEPCOPY" "$ROOT/k8s-operator/$DEEPCOPY"
  echo "gen-manifests: wrote k8s-manifests/base/01-crd.yaml, the chart's CRD and k8s-operator/$DEEPCOPY"
  exit 0
fi
rc=0
diff -u "$CRD_OUT" "$work/01-crd.yaml" || { echo "gen-manifests: 01-crd.yaml is not what the markers generate" >&2; rc=1; }
diff -u "$CHART_CRD" "$work/01-crd.yaml" || { echo "gen-manifests: the chart's CRD is not what the markers generate" >&2; rc=1; }
diff -u "$ROOT/k8s-operator/$DEEPCOPY" "$work/op/$DEEPCOPY" || { echo "gen-manifests: $DEEPCOPY is stale" >&2; rc=1; }
[ "$rc" -eq 0 ] && echo "gen-manifests: generated code is current"
[ "$rc" -eq 0 ] || echo "gen-manifests: run 'make manifests' and commit the result" >&2
exit "$rc"
